"""
Django settings for reface project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3tb7)br4v^l2w@=nj!%%k4u6(mgg)9jjlqf-&i#=e@!k-nmjx%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO','https')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'reface_main',
]

MIDDLEWARE = [
        'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
]

ROOT_URLCONF = 'reface.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reface.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', 
        'NAME' : 'reface', 
        'USER' : 'reface', 
        'PASSWORD': 'reface', 
        'HOST' : '10.47.96.3', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

from google.cloud import storage
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'reface'
STORAGE_CLIENT = storage.Client()

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
CORS_ALLOW_HEADERS = (
            'accept',
                'accept-encoding',
                    'authorization',
                        'content-type',
                            'dnt',
                                'origin',
                                    'user-agent',
                                        'x-csrftoken',
                                            'x-CSRFToken',
                                                'X-CSRFToken',
                                                    'csrftoken',
                                                        'x-requested-with',
                                                        )

CORS_ALLOW_METHODS = (
            'DELETE',
                'GET',
                    'OPTIONS',
                        'PATCH',
                            'POST',
                            'PUT',
                            )
CSRF_COOKIE_NAME = "csrftoken"
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_AGE = 1000
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE =True
CRSF_COOKIE_SAMESITE = None

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

#CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
               # 'http://localhost:3000',
                          # 'http://127.0.0.1:3000',
                          )

CORS_ORIGIN_REGEX_WHITELIST = [
          #  'http://localhost:3000',
            #  'http://127.0.0.1:3000'
                ]
EST_FRAMEWORK ={
                'DEFAULT_PERMISSION_CLASSES':[
                                ],
                        'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.LimitOffsetPagination',
                                'PAGE_SIZE': 10,
                                        }
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
CLOUD_ROOT = 'https://storage.googleapis.com/reface/'
STATIC_ROOT = os.path.join(BASE_DIR,'static/')

STATIC_URL = '/static/'
